# Generated by Django 5.2.7 on 2025-10-18 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('JEFE', 'Jefe'), ('JEFE_SEMANAL', 'Jefe Semanal'), ('DOMINIO', 'Dominio')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='farm.game')),
            ],
            options={
                'unique_together': {('name', 'game')},
            },
        ),
        migrations.CreateModel(
            name='FarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_type', models.CharField(choices=[('JEFE', 'Jefe'), ('JEFE_SEMANAL', 'Jefe Semanal'), ('DOMINIO', 'Dominio')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmsource')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_events', to='farm.game')),
            ],
        ),
    ]
