# Generated by Django 5.2.7 on 2025-10-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_type', models.CharField(choices=[('JEFE', 'Jefe'), ('JEFE-SEMANAL', 'Jefe Semanal'), ('DOMINIO', 'Dominio')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rarity', models.CharField(choices=[('COMUN', 'Común'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LEGENDARIO', 'Legendario')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FarmSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('JEFE', 'Jefe'), ('JEFE-SEMANAL', 'Jefe Semanal'), ('DOMINIO', 'Dominio')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
