# Generated by Django 5.2.7 on 2025-10-27 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmdrop',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='farm.farmevent'),
        ),
        migrations.AddField(
            model_name='farmdrop',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmreward'),
        ),
        migrations.AddField(
            model_name='farmreward',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='farm.farmsource'),
        ),
        migrations.AddField(
            model_name='farmevent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmsource'),
        ),
        migrations.AddField(
            model_name='farmsource',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='farm.game'),
        ),
        migrations.AddField(
            model_name='farmevent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_events', to='farm.game'),
        ),
        migrations.AlterUniqueTogether(
            name='farmreward',
            unique_together={('name', 'rarity', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='farmsource',
            unique_together={('name', 'game')},
        ),
    ]
