# Generated by Django 5.2.7 on 2025-10-19 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rarity', models.CharField(choices=[('COMUN', 'Común'), ('RARO', 'Raro'), ('EPICO', 'Épico'), ('LEGENDARIO', 'Legendario')], max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='farm.farmsource')),
            ],
        ),
    ]
