# Generated by Django 5.2.7 on 2025-10-19 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farmreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='farm.farmevent')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmreward')),
            ],
        ),
    ]
